const easyWords = [
    "team", "small", "group", "people", "wanted", "map", "slow", "happy", "sad", "make", 
    "something", "useful", "came", "together", "ideas", "plans", "everyone", "own", "way", 
    "helping", "over", "time", "more", "joined", "bringing", "skills", "knowledge", "project", 
    "always", "easy", "because", "there", "were", "many", "challenges", "but", "never", "stopped", 
    "working", "each", "person", "had", "important", "role", "play", "they", "all", "hard", "from", 
    "morning", "night", "trying", "reach", "goals", "saw", "progress", "gave", "motivation", "keep", 
    "moving", "forward", "results", "getting", "good", "bad", "loud", "quiet", "better", "pushed", 
    "even", "would", "meet", "groups", "talk", "problems", "faced", "how", "fix", "shared", "ideas", 
    "found", "solutions", "helped", "grow", "knew", "stayed", "strong", "could", "achieve", "anything", 
    "trusted", "others", "best", "took", "on", "every", "problem", "solved", "it", "one", "step", 
    "sometimes", "split", "into", "smaller", "teams", "focus", "different", "tasks", "helped", "get", 
    "done", "faster", "learned", "improved", "every", "task", "kept", "getting", "better", "worked", 
    "there", "was", "always", "something", "new", "learn", "everyone", "eager", "improve", "their", 
    "skills", "bigger", "became", "complex", "ready", "challenge", "believed", "doing", "hard", 
    "work", "would", "worth", "pressure", "high", "but", "gave", "found", "joy", "working", "together", 
    "even", "tough", "times", "there", "were", "moments", "fun", "laughed", "shared", "stories", 
    "encouraged", "each", "other", "day", "chance", "grow", "slowly", "surely", "saw", "vision", "come", 
    "life", "piece", "paying", "off", "could", "see", "others", "progress", "wanted", "join", "inspiring", 
    "everyone", "around", "them", "welcomed", "new", "members", "kept", "stronger", "passing", "supported", 
    "every", "possible", "create", "dream", "reality", "finally", "reached", "goal", "pride", "happiness", 
    "felt", "beyond", "words", "done", "something", "big", "just", "about", "end", "result", "journey", 
    "taken", "learned", "became", "better", "people", "along", "way", "faced", "every", "challenge", 
    "found", "ways", "overcome", "everything", "stronger", "now", "ready", "whatever", "came", "next", 
    "hard", "paid", "off", "ways", "never", "imagined", "knew", "future", "could", "take", "bigger", 
    "box", "car", "cat", "projects", "succeed", "become", "not", "just", "family", "working", "toward", 
    "common", "goal", "every", "step", "helped", "celebrated", "victories", "learned", "mistakes", 
    "created", "special", "would", "last", "years", "come", "with", "new", "task", "took", "proven", 
    "themselves", "others", "when", "people", "shared", "purpose", "anything", "possible", "felt", "proud", 
    "done", "knew", "would", "always", "carry", "lessons", "learned", "into", "future", "success", "built", 
    "trust", "teamwork", "never", "giving", "up", "dream", "journey", "was", "also", "full", "joy", 
    "growth", "faced", "challenges", "solved", "problems", "achieved", "goal", "together", "made", 
    "something", "would", "remembered", "appreciated", "long", "time", "dedication", "each", "made", 
    "difference", "ready", "take", "whatever", "came", "next", "grown", "individuals", "accomplish", 
    "even", "more", "journey", "over", "just", "beginning", "something", "bigger", "better", "increase", 
    "decrease", "enhance", "diminish", "expand", "contract", "boost", "reduce", "elevate", "lower", 
    "amplify", "minimize", "grow", "shrink", "transform", "dog", "adjust", "modify", "shift", "change", 
    "develop", "progress", "regress", "rise", "fall", "escalate", "decline", "stabilize", "fluctuate", 
    "modify", "refine", "optimize", "adapt", "innovate", "create", "generate", "produce", "yield", 
    "harvest", "cultivate", "initiate", "launch", "execute", "implement", "strategize", "plan", "coordinate", 
    "collaborate", "contribute", "support", "assist", "facilitate", "encourage", "inspire", "motivate", 
    "challenge", "reflect", "analyze", "evaluate", "assess", "prioritize", "organize", "streamline", 
    "balance", "strengthen", "apple", "banana", "orange", "grape", "chair", "table", "house", "road", 
    "book", "pen", "paper", "sun", "moon", "star", "water", "fire", "tree", "flower", "bird", "fish", 
    "cat", "dog", "jump", "run", "walk", "sit", "stand", "laugh", "cry", "play", "work", "sleep", 
    "eat", "drink", "read", "write", "draw", "sing", "dance", "listen", "talk", "help", "share", "smile", 
    "think", "dream", "build", "create", "explore", "baby", "ball", "bed", "bike", "fan", "flag", "game", 
    "hand", "hat", "leg", "ant", "bat", "cap", "dog", "egg", "fox", "hat", "ink", "jar", "key", "log", 
    "mat", "net", "owl", "pan", "quilt", "rat", "sun", "top", "van", "web", "zip", "balloon", "cake", 
    "doll", "elephant", "guitar", "helicopter", "ice", "jacket", "kite", "lamp", "muffin", "necklace", 
    "octopus", "pillow", "quokka", "rocket", "socks", "teddy", "unicorn", "vase", "whale", "xylophone", 
    "yarn", "zebra", "airplane", "bicycle", "candle", "cloud", "cucumber", "daisy", "ear", "feather", 
    "glove", "hammer", "igloo", "jelly", "keychain", "lollipop", "mango", "nose", "ocean", "pasta", 
    "quilt", "rainbow", "sand", "turtle", "umbrella", "volcano", "whistle", "ray", "yogurt", "zucchini", 
    "candy", "pillow", "spoon", "fork", "knife", "bowl", "plate", "cup", "taco", "pizza", "burger", 
    "cookie", "fruit", "vegetable", "cereal", "soda", "juice", "milk", "tea", "coffee", "chocolate", 
    "popcorn"
];

let hardWords = [
    "initiative", "commenced", "consortium", "individuals", "aspired", "innovate", "consolidated", 
    "expertise", "conceptualized", "multifaceted", "project", "participant", "contributed", 
    "specialized", "knowledge", "insights", "endeavor", "progressed", "additional", "collaborators", 
    "contributing", "diverse", "skills", "perspectives", "undertaking", "difficulties", 
    "impediments", "persevered", "unwavering", "resolve", "collective", "effort", "instrumental", 
    "overcoming", "obstacles", "navigating", "adversities", "pivotal", "advancing", "meticulous", 
    "planning", "execution", "engaged", "extensive", "discourse", "analysis", "address", 
    "challenges", "refine", "strategies", "iterative", "evaluations", "facilitated", "incremental", 
    "improvements", "gradually", "evolved", "complexities", "increased", "expanded", "group", 
    "tackled", "increasingly", "sophisticated", "tasks", "commitment", "remained", "steadfast", 
    "embraced", "methodologies", "adapted", "circumstances", "necessitated", "rigorous", "problem", 
    "solving", "innovative", "thinking", "contribution", "optimizing", "performance", "collaboration", 
    "fostered", "environment", "mutual", "support", "intellectual", "exchange", "enabling", 
    "surmount", "achieve", "milestones", "shared", "experiences", "continuous", "learning", 
    "integral", "progress", "development", "culmination", "efforts", "marked", "significant", 
    "achievements", "breakthroughs", "success", "testament", "diligence", "accomplishments", 
    "garnered", "recognition", "inspired", "exploration", "advancement", "field", "intricate", 
    "nature", "demanded", "sustained", "focus", "adaptability", "navigated", "complex", "scenarios", 
    "requirements", "attributed", "strategic", "approach", "cohesive", "teamwork", "challenge", 
    "encountered", "solution", "oriented", "mindset", "characterized", "series", "refinements", 
    "resulting", "robust", "outcome", "dedication", "perseverance", "realizing", "vision", 
    "objectives", "reflection", "collective", "spirit", "impact", "extended", "initial", "scope", 
    "influencing", "subsequent", "developments", "setting", "precedent", "future", "ability", 
    "thrive", "face", "underscored", "proficiency", "resilience", "experience", "enriched", 
    "capabilities", "prepared", "pursuits", "journey", "marked", "growth", "landscape", "complexity", 
    "success", "result", "vision", "commitment", "phase", "overall", "demonstrated", "capacity", 
    "handling", "challenging", "tasks", "served", "catalyst", "benchmark", "opened", "avenues", 
    "development", "rigor", "instrumental", "paving", "continued", "excellence", "exemplified", 
    "power", "strategic", "thinking", "remarkable", "groundbreaking", "advancements", "interdisciplinary", 
    "contributions", "transformative", "solutions", "enhanced", "methodologies", "elevating", 
    "standards", "technologies", "global", "synergistic", "collaborations", "visionary", "approaches", 
    "paradigm", "shifts", "frameworks", "disruptive", "trends", "advanced", "research", "systemic", 
    "improvements", "proactive", "measures", "comprehensive", "analyses", "stakeholder", "engagement", 
    "thought", "leadership", "dynamic", "interactions", "fostering", "creativity", "adaptive", 
    "strategies", "cutting", "edge", "holistic", "perspectives", "forward", "initiatives", 
    "synergistic", "paradigmatic", "heuristic", "epistemological", "ontological", "transformative", 
    "ideation", "optimization", "stratagems", "methodologies", "extrapolation", "juxtaposition", 
    "facilitation", "synthesis", "articulation", "cognizance", "discernment", "acumen", "scalability", 
    "transdisciplinary", "innovation", "dynamism", "resilience", "fortitude", "acuity", "amelioration", 
    "ascertainment", "catalystic", "conundrum", "convergence", "corroboration", "deconstruction", 
    "dichotomy", "dissemination", "empirical", "encompassing", "epistemic", "formulation", 
    "heuristics", "incorporation", "interdisciplinary", "metamorphosis", "multidimensional", 
    "perpetuation", "proliferation", "quantitative", "recapitulation", "recontextualization", 
    "sophistication", "sustainability", "transformation", "utilitarianism", "abstruse", "acquiescence", 
    "adjudication", "alacrity", "anomalous", "antithesis", "apprehension", "articulation", "ascertain", 
    "asymmetry", "augmentation", "axiomatic", "benevolence", "capitulation", "cognizant", "commensurate", 
    "conflation", "conjecture", "consolidation", "contemplation", "correlation", "culmination", 
    "deference", "delineation", "derivation", "dissonance", "dynamics", "efficacy", "elucidation", 
    "emergent", "enigma", "ephemeral", "equanimity", "exegesis", "extrapolate", "facilitative", 
    "formidable", "heuristic", "imminent", "imperturbable", "incumbent", "inexorable", "insidious", 
    "interstitial", "juxtapose", "meticulousness", "nuance", "parochial", "pervasive", "quintessential", 
    "aberration", "acumen", "adventitious", "allegorical", "ameliorate", "anathema", "antipathy", 
    "apotheosis", "ascetic", "asynchronous", "attenuate", "axiom", "bellicose", "catalytic", "cogent", 
    "commensurable", "conflation", "conjectural", "conspicuous", "contingency", "corollary", 
    "debilitate", "deference", "dichotomous", "disparate", "effulgent", "epiphany", "equivocate", 
    "exacerbate", "exemplary", "fortuitous", "germane", "harbinger", "heterogeneous", "iconoclast", 
    "idiosyncratic", "impediment", "inchoate", "infallible", "inscrutable", "interlocutor", 
    "juxtaposition", "languid", "metaphysical", "nebulous", "paradigm", "quagmire", "recalcitrant", 
    "taciturn"
  ];
  
